### ISSUE TITLE
[FEATURE] Command API

### ISSUE THREAD

**Issue by danieleguglietti** [FutureTeam-IT/FutureAPI#3]
### Your Idea

```Markdown
Create a Command API compatible with both Bukkit and Velocity.
It has to manage command execution and completion.
It requires to work with Minecraft 1.13
```

### Tasks

- [x] Abstract Command
  - [ ] Execution
  - [ ] Completion
  - [x] Sub Commands
 - [ ] Command Handler

**Comment by Maxigame99** [comment]
Velocity mai usato, preferisci comunque che provi a farlo io?

**Comment by danieleguglietti** [comment]
> Velocity mai usato, preferisci comunque che provi a farlo io?

La facciamo insieme, non c'è bisogno di conoscerlo bene velocity,  puoi confrontare la [wiki](https://velocitypowered.com/wiki/developers/command-api/). Comunque servirà modificare di nuovo la struttura del progetto dividento l'api dalle implementazioni. Per ora la lasciamo qui come semplice to-do. Prima voglio fare altro... (la struttura va comunque modificata :/)
